/*
 * Licensed to the IntelliSQL Project under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The IntelliSQL Project licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.intellisql.jdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.UUID;
import java.util.concurrent.Executor;

import org.apache.calcite.avatica.remote.Service;

import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

/** JDBC Connection implementation for IntelliSql. */
@Slf4j
@Getter
public class IntelliSqlConnection implements Connection {

    private static final String IS_CLOSED = "Connection is closed";

    private final AvaticaClient client;

    private final JdbcUrlParser urlParser;

    private final String connectionId;

    private final Properties properties;

    private boolean closed;

    private SQLWarning warningChain;

    /**
     * Creates a new connection.
     *
     * @param client the Avatica client
     * @param urlParser the URL parser
     * @param properties the connection properties
     */
    public IntelliSqlConnection(
                                final AvaticaClient client, final JdbcUrlParser urlParser, final Properties properties) {
        this.client = client;
        this.urlParser = urlParser;
        this.properties = properties;
        this.connectionId = UUID.randomUUID().toString();
        openConnection();
    }

    private void openConnection() {
        Map<String, String> info = new HashMap<>();
        for (String key : properties.stringPropertyNames()) {
            info.put(key, properties.getProperty(key));
        }
        client.openConnection(connectionId, info);
        log.info("Opened connection: {}", connectionId);
    }

    @Override
    public Statement createStatement() throws SQLException {
        checkClosed();
        Service.CreateStatementResponse response = client.createStatement(connectionId);
        return new IntelliSqlStatement(this, response.statementId);
    }

    @Override
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency) throws SQLException {
        checkClosed();
        return createStatement();
    }

    @Override
    public Statement createStatement(
                                     final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) throws SQLException {
        checkClosed();
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(final String sql) throws SQLException {
        checkClosed();
        long maxRows = getLongProperty("maxRows", 0);
        Service.PrepareResponse response = client.prepare(connectionId, sql, maxRows);
        return new IntelliSqlPreparedStatement(this, response.statement, sql);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency) throws SQLException {
        checkClosed();
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(
                                              final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) throws SQLException {
        checkClosed();
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int autoGeneratedKeys) throws SQLException {
        checkClosed();
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int[] columnIndexes) throws SQLException {
        checkClosed();
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final String[] columnNames) throws SQLException {
        checkClosed();
        return prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(final String sql) throws SQLException {
        throw new SQLException("CallableStatement not supported - no stored procedures");
    }

    @Override
    public CallableStatement prepareCall(final String sql, final int resultSetType, final int resultSetConcurrency) throws SQLException {
        throw new SQLException("CallableStatement not supported - no stored procedures");
    }

    @Override
    public CallableStatement prepareCall(
                                         final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) throws SQLException {
        throw new SQLException("CallableStatement not supported - no stored procedures");
    }

    @Override
    public String nativeSQL(final String sql) throws SQLException {
        checkClosed();
        return sql;
    }

    @Override
    public void setAutoCommit(final boolean autoCommit) throws SQLException {
        checkClosed();
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        checkClosed();
        return true;
    }

    @Override
    public void commit() throws SQLException {
        checkClosed();
    }

    @Override
    public void rollback() throws SQLException {
        checkClosed();
    }

    @Override
    public void rollback(final Savepoint savepoint) throws SQLException {
        throw new SQLException("Savepoints not supported");
    }

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        try {
            client.closeConnection(connectionId);
            log.info("Closed connection: {}", connectionId);
            // CHECKSTYLE:OFF: IllegalCatch
        } catch (final Exception ex) {
            // CHECKSTYLE:ON: IllegalCatch
            log.warn("Error closing connection", ex);
        } finally {
            closed = true;
        }
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        checkClosed();
        return new IntelliSqlDatabaseMetaData(this);
    }

    @Override
    public void setReadOnly(final boolean readOnly) throws SQLException {
        checkClosed();
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        checkClosed();
        return false;
    }

    @Override
    public void setCatalog(final String catalog) throws SQLException {
        checkClosed();
    }

    @Override
    public String getCatalog() throws SQLException {
        checkClosed();
        return urlParser.getDatabase();
    }

    @Override
    public void setTransactionIsolation(final int level) throws SQLException {
        checkClosed();
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        checkClosed();
        return TRANSACTION_NONE;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        checkClosed();
        return warningChain;
    }

    @Override
    public void clearWarnings() throws SQLException {
        checkClosed();
        warningChain = null;
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        checkClosed();
        return new HashMap<>();
    }

    @Override
    public void setTypeMap(final Map<String, Class<?>> map) throws SQLException {
        checkClosed();
    }

    @Override
    public void setHoldability(final int holdability) throws SQLException {
        checkClosed();
    }

    @Override
    public int getHoldability() throws SQLException {
        checkClosed();
        return ResultSet.HOLD_CURSORS_OVER_COMMIT;
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        throw new SQLException("Savepoints not supported");
    }

    @Override
    public Savepoint setSavepoint(final String name) throws SQLException {
        throw new SQLException("Savepoints not supported");
    }

    @Override
    public void releaseSavepoint(final Savepoint savepoint) throws SQLException {
        throw new SQLException("Savepoints not supported");
    }

    @Override
    public Clob createClob() throws SQLException {
        throw new SQLException("Clob not supported");
    }

    @Override
    public Blob createBlob() throws SQLException {
        throw new SQLException("Blob not supported");
    }

    @Override
    public NClob createNClob() throws SQLException {
        throw new SQLException("NClob not supported");
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        throw new SQLException("SQLXML not supported");
    }

    @Override
    public boolean isValid(final int timeout) throws SQLException {
        if (timeout < 0) {
            throw new SQLException("Timeout must be >= 0");
        }
        return !closed;
    }

    @Override
    public void setClientInfo(final String name, final String value) throws SQLClientInfoException {
        properties.setProperty(name, value);
    }

    @Override
    public void setClientInfo(final Properties properties) throws SQLClientInfoException {
        this.properties.putAll(properties);
    }

    @Override
    public String getClientInfo(final String name) throws SQLException {
        checkClosed();
        return properties.getProperty(name);
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        checkClosed();
        Properties copy = new Properties();
        copy.putAll(properties);
        return copy;
    }

    @Override
    public Array createArrayOf(final String typeName, final Object[] elements) throws SQLException {
        throw new SQLException("Array not supported");
    }

    @Override
    public Struct createStruct(final String typeName, final Object[] attributes) throws SQLException {
        throw new SQLException("Struct not supported");
    }

    @Override
    public void setSchema(final String schema) throws SQLException {
        checkClosed();
    }

    @Override
    public String getSchema() throws SQLException {
        checkClosed();
        return urlParser.getDatabase();
    }

    @Override
    public void abort(final Executor executor) throws SQLException {
        close();
    }

    @Override
    public void setNetworkTimeout(final Executor executor, final int milliseconds) throws SQLException {
        checkClosed();
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        checkClosed();
        return 0;
    }

    void addWarning(final SQLWarning warning) {
        if (warningChain == null) {
            warningChain = warning;
        } else {
            warningChain.setNextWarning(warning);
        }
    }

    private void checkClosed() throws SQLException {
        if (closed) {
            throw new SQLException(IS_CLOSED);
        }
    }

    long getLongProperty(final String key, final long defaultValue) {
        String value = properties.getProperty(key);
        if (value != null) {
            try {
                return Long.parseLong(value);
            } catch (final NumberFormatException ex) {
                log.warn("Invalid value for property {}: {}", key, value);
            }
        }
        return defaultValue;
    }

    int getIntProperty(final String key, final int defaultValue) {
        String value = properties.getProperty(key);
        if (value != null) {
            try {
                return Integer.parseInt(value);
            } catch (final NumberFormatException ex) {
                log.warn("Invalid value for property {}: {}", key, value);
            }
        }
        return defaultValue;
    }

    @Override
    public <T> T unwrap(final Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("Not a wrapper for " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(final Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }
}
